name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check formatting
      run: cargo fmt --all --verbose -- --check
    - name: Ask Clippy for his thoughts
      run: cargo clippy --all-targets --all-features
    - name: Run tests
      run: cargo test --verbose
